#!/bin/bash

apply() {
  gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/balaswecha-dark.png"

  gsettings set com.canonical.Unity.Launcher favorites  "['application://pencilbox.desktop', 'application://nautilus.desktop', 'application://chromium-browser.desktop', 'application://libreoffice-writer.desktop', 'application://libreoffice-calc.desktop', 'application://libreoffice-impress.desktop', 'application://openshot.desktop', 'application://audacity.desktop', 'application://chrome-eealagocaipaflcjmeapmobpmilffopi-Default.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  echo "Successfully applied the skin"
}

reset() {
  gsettings reset org.gnome.desktop.background picture-uri
  gsettings reset com.canonical.Unity.Launcher favorites
  echo "Reset Successful"
}

manual() {
  echo -e "balaswecha-skin - apply or remove balaswecha icons and wallpaper pack\nUsage: balaswecha-skin [apply] [reset] [-h]\n\tapply - apply the pack\n\treset - reset to the OS default\n\t-h - help"
}

if [[ $1 = "apply" ]]; then
  apply
  exit 0
elif [[ $1 = "reset" ]]; then
  reset
  exit 0
elif [[ $1 = "-h" ]]; then
  manual
  exit 0
elif [[ $1 = "" ]]; then
  apply
  exit 0
else
  manual
  exit 0
fi
