#!/bin/bash

apply() {
  gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/balaswecha-dark.png"
  if [[ $1 = "teacher" ]]; then
    apply_teacher_skin
  else
    apply_student_skin
  fi
}

apply_teacher_skin() {
 gsettings set com.canonical.Unity.Launcher favorites  "['application://pencilbox.desktop', 'application://nautilus.desktop', 'application://chromium-browser.desktop', 'application://libreoffice-writer.desktop', 'application://libreoffice-calc.desktop', 'application://libreoffice-impress.desktop', 'application://openshot.desktop', 'application://audacity.desktop', 'application://chrome-eealagocaipaflcjmeapmobpmilffopi-Default.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  echo "Successfully applied the skin for teachers"
}

apply_student_skin() {
  gsettings set com.canonical.Unity.Launcher favorites  "['application://physics.desktop','application://physics.desktop','application://chemistry.desktop','application://mathematics.desktop','application://english.desktop','application://social.desktop']"
  echo "Successfully applied the skin for students"
}

reset() {
  gsettings reset org.gnome.desktop.background picture-uri
  gsettings reset com.canonical.Unity.Launcher favorites
  echo "Reset Successful"
}

manual() {
  echo -e "balaswecha-skin - apply or remove balaswecha icons and wallpaper
  pack\nUsage: balaswecha-skin [ apply [teacher|student] ] [reset] [-h]\n\tapply - apply the pack\n\treset - reset to the OS default\n\t-h - help"
}

if [[ $1 = "apply" ]]; then
  apply $2
  exit 0
elif [[ $1 = "reset" ]]; then
  reset
  exit 0
elif [[ $1 = "-h" ]]; then
  manual
  exit 0
elif [[ $1 = "" ]]; then
  apply
  exit 0
else
  manual
  exit 0
fi
