$apps=[
  {
    "launcher_name"=>"Balloons and Buoyancy",
    "name"=>"balloons-and-buoyancy",
    "jar_url"=>"ideal-gas/balloons-and-buoyancy_en.jar",
    "icon_url"=>"ideal-gas/balloons-and-buoyancy-128.png",
    "ldesc"=>"Experiment with a helium balloon, a hot air balloon, or a rigid sphere filled with different gases",
    "desc"=>"Discover what makes some balloons float and others sink.",
    "dependencies"=> ["java-runtime"],
  },
  {
      "launcher_name"=>"Alpha Decay",
      "name"=>"alpha-decay",
      "jar_url"=>"nuclear-physics/alpha-decay_en.jar",
      "icon_url"=>"ideal-gas/alpha-decay-128.png",
      "ldesc"=>"Watch alpha particles escape from a polonium nucleus, causing radioactive alpha decay.",
      "desc"=>"See how random decay times relate to the half life.",
      "dependencies"=> ["java-runtime"],
  },
  {
      "launcher_name"=>"Atomic Interactions",
      "name"=>"atomic-interaction",
      "jar_url"=>"states-of-matter/atomic-interactions_en.jar",
      "icon_url"=>"states-of-matter/atomic-interactions-128.png",
      "ldesc"=>"Explore the interactions between various combinations of two atoms. Turn on the force arrows to see either the total force acting on the atoms or the individual attractive and repulsive forces.",
      "desc"=>"Try the Adjustable Attraction atom to see how changing the parameters affects the interaction.",
      "dependencies"=> ["java-runtime"],
  },
  {
      "launcher_name"=>"Band Structure",
      "name"=>"band-structure",
      "jar_url"=>"bound-states/band-structure_en.jar",
      "icon_url"=>"bound-states/band-structure-128.png",
      "ldesc"=>"Explore the origin of energy bands in crystals of atoms.",
      "desc"=>"The structure of these bands determines how materials conduct electricity.",
      "dependencies"=> ["java-runtime"],
  },
  {
      "launcher_name"=>"Battery-Resistor Circuit",
      "name"=>"battery-resistor-circuit",
      "jar_url"=>"battery-resistor-circuit/battery-resistor-circuit_en.jar",
      "icon_url"=>"battery-resistor-circuit/battery-resistor-circuit-128.png",
      "ldesc"=>"Look inside a resistor to see how it works. Increase the battery voltage to make more electrons flow though the resistor. Increase the resistance to block the flow of electrons.",
      "desc"=>" Watch the current and resistor temperature change.",
      "dependencies"=> ["java-runtime"],
  },
]